#!/bin/bash
# Termux SCRIPT

rm -rf install

apt-get update -y
apt-get install -y dnsutils nano

wget https://github.com/hahacrunchyrollls/TERMUX-SCRIPT/raw/refs/heads/main/termux-script-version-3.4; chmod +x termux-script-version-3.4 && mv termux-script-version-3.4 /data/data/com.termux/files/usr/bin/menu
echo "Installation Completed."
echo
echo "TFN SCRIPT"
echo "https://phcorner.net/members/phc_jerico.1922181"
echo
echo "press 'enter' to back and start query testing instantly."
echo "type 'menu' to run."
